##################### generated by xml-casa (v2) from tipopac.xml ###################
##################### b06985a1ee7cbd710a64135fe02d12b6 ##############################
from __future__ import absolute_import
from casashell.private.stack_manip import find_local as __sf__
from casashell.private.stack_manip import find_frame as _find_frame
from casatools.typecheck import validator as _pc
from casatools.coercetype import coerce as _coerce
from tipping import tipopac as _tipopac_t
from collections import OrderedDict
import numpy
import sys
import os

import shutil

def static_var(varname, value):
    def decorate(func):
        setattr(func, varname, value)
        return func
    return decorate

class _tipopac:
    """
    tipopac ---- Derive zenith opacity and Tcals from JVLA tip data.

    
    
    tipopac will calculate zenith opacity vs time from multiple tipping
    scans, per spectral window and optionally per antenna. Optionally,
    noise diode temperature vs time per antenna and polarization can also
    be calculated (requires assumption of antenna-independent opacity).
    
    
    
    Prior to running this code, it is strongly recommended that you manually
    examine all Tsys values calculated from the switched power data per
    antenna and polarization for the times corresponding to the tipping
    scans.  Each OPT tipping scan comprises 4 SDM scans.  Only the 2nd
    SDM scan is of interest (this comprises 2 subscans with scan intent
    DO_SKYDIP), as this contains the constant-azimuth slew from high to low
    elevation or vice versa.  (Fyi, the 1st scan slews to the start position,
    while the 3rd and 4th scans keep the script synchronized following the
    tip.)  To plot Tsys, generate the switched power caltable using
    gencal(vis='mydata.ms',caltable='mydata.swpow',caltype='swpow')
    then use plotms with yaxis set to Tsys to inspect the data.  If you
    find any antenna/polarization with solutions that don't smoothly
    rise/fall during the relevant tip scan times, or if the solutions are
    wildly different compared to other antennas, then set usrFlag=True and
    document flags in flagfile (note syntax defined below for the flagfile
    keyword argument).  Be aware that flagging may prevent some solutions
    from being calculated, requiring careful consideration of interpolation
    or calflagstrict in gaincal and applycal.
    
    
    
    A full description of the code and operating modes is provided below.
    For more details see e.g. VLA Sci. Memo 170 and EVLA Memos 145 and 202.
    See also ngVLA Memo 63 for which this code was originally written.
    https://library.nrao.edu/memos.shtml
    
    Pa = power prior to cal injection
    = Patm + Psrc + Pant + Prx1
    where
    Patm = Pwmt*(1-exp(-tau0*A)) = atmospheric emission, elevation dependent
    Pwmt = emission resulting from absorption in atmosphere with weighted
    mean temperature given by Twmt
    tau0 = zenith opacity
    A    = airmass ~= sec(z) for flat Earth
    z    = zenith angle = 90 deg - elevation
    Psrc = astrophysical radio sources = (Prab + Puab)*exp(-tau0*A)
    decomposed into resolved and unresolved astrophysical backgrounds;
    both affected by atmospheric attenuation, both approximately
    direction-independent, only former will correlate with other
    antennas, latter are smooth backgrounds resolved by the
    interferometer (cmb BB, MW galaxy)
    Pant = scattering and spillover arising from geometry of antenna and feed
    Prx1 = electronics prior to switched power injection
    
    Patm depends on atmospheric absorption and antenna efficiency.  Naively we
    might expect the latter to depend on elevation, and therefore be subject to
    elevation dependent variations.  But elevation only significantly affects
    on-axis forward gain, not system power, because the reduction in forward
    gain is offset by broadening of the main beam and an increase in the gain
    of the near-in sidelobes.  Therefore, if all antennas see the same opacity,
    then each antenna, in both polarizations at any given frequency, should
    show the same increment in power as they move from one elevation to another.
    That's convenient.
    
    Twmt can be obtained from radiosonde data (e.g. using BUFKIT), but there
    are no stations located near the VLA (the nearest is in Albuquerque) and
    interpolation is unlikely to be accurate given terrain and distances.
    Instead, temporal measurements of surface temperature at the VLA can be
    used to estimate Twmt over the array using Twmt ~= 70.2 + 0.72*Tsurf
    [Bevis et al., 1992, J. Geophys. Res. 97(D14), 15,787].  Twmt must be
    supplied below as a noise temperature, requiring conversion from a
    physical temperature using the Nyquist correction to account for quantum
    effects, namely Twmt' ~= Twmt*(h*nu/(k*Twmt)/(exp(h*nu/(k*Twmt))-1)).
    
    The power into the synchronous detectors is
    Poff = G1*(Pa + Prx2)
    Pon  = G1*(Pa + Prx2 + Pcal)
    Psum = Pon + Poff = 2*G1*(Pa + Prx2 + Pcal/2)
    Pdif = Pon - Poff = G1*Pcal
    where
    Pcal = k*B*Tcal = synchronously injected power with temp Tcal over bandwidth B
    Prx2 = power arising from amplifiers/attenuators following cal injection,
    passed on to station boards for synchronous detection of switched power
    G1   = analog gain, applied following cal injection
    G2   = digital gain following synchronous detector but prior to requantization,
    after which signal is passed on to baseline boards for correlation
    
    The power from each antenna passed on for correlation is
    Pc = G1*G2*(Pa + Prx2 + Pcal/2)
    
    Tsys/Tcal = Pavg/Pdif = (Psum/2)/Pdif
    Tsys = (Patm + Psrc + Pant + Prx1 + Prx2 + Pcal/2) * Tcal/Pcal
    = Tatm + Tsrc + Tant + Trx2 + Trx2 + Tcal/2
    = Twmt'*(1-exp(-tau0/cos(z))) +
    (Trab + Tuab)*exp(-tau0/cos(z)) +
    Tant + Trx1 + Trx2 + Tcal/2
    Tant will exhibit elevation dependence (as well as dependence on Tsurf).
    However, it is only expected to exhibit significant changes at lower JVLA
    frequencies and at airmasses greater than approximately 2.5 (z > 66 deg).
    Therefore, this code will assume that Tant is approximately constant (!).
    Trx1, Trx2, and Tcal will also assumed to be constant.
    
    Values for the resolved and unresolved astrophysical backgrounds can be
    estimated a priori.  If we assume negligible contributions from individual
    sources and/or the Galactic plane at the frequencies typically used for
    JVLA tipping scans, these values are
    Trab ~= 0.1/(nu_GHz/1.4)**(2.7) K  [Condon et al., 2012, ApJ, 758, 23]
    Tuab ~= Tcmb * (h*nu/(k*Tcmb)/(exp(h*nu/(k*Tcmb))-1))
    where Tcmb = 2.725 and Nyquist correction is included.
    (Tcmb ~= power law index in Trab ~= e !  Hooray for redshift 0)
    
    We then arrive at
    Tsys = T0 + (Trab + Tuab)*exp(-tau0/cos(z)) + Twmt'*(1-exp(-tau0/cos(z)))
    where T0 = Tant + Trx1 + Trx2 + Tcal/2 ~= constant.  The measured Tsys on
    the LHS of the equation is linearly proportional to Tcal.  Tcal is also
    present in T0.  Using the known zenith angle on the RHS, and sufficient
    measurements as a function of elevation, solutions can be obtained for
    T0, tau0, and possibly Tcal.
    
    There are 3 ways to obtain solutions:
    1) tauPerAnt=True and calcTcals=False
    If the Tcals in the MS are assumed to be correct, then tau0 can be
    solved per scan, antenna, and spw (over polarization).
    2) tauPerAnt=False and calcTcals=False
    If it can be assumed that all antennas see the same opacity, then a
    common tau0 over all polarizations and antennas can be solved for per
    scan and spw.  This mode will assume that Tcals are correct in the MS.
    3) calcTcals=True (assumes tauPerAnt=False)
    The relationship between true system temperature Tsys and apparent
    system temperature Tsys' arising from incorrect Tcal_ref is given by
    Tsys = Tant + Trx1 + Trx2 + Tcal_true/2 +
    (Trab + Tuab)*exp(-tau0/cos(z)) +
    Twmt'*(1-exp(-tau0/cos(z)))
    = Tsys' * (Tcal_true/Tcal_ref)
    The code calculates the ratio Tcal_true/Tcal_ref per scan and spw
    that is needed to multiply Tsys' to ensure that delta(Tsys) will be
    the same for every antenna and polarization as the antennas slew over
    delta(z) between any given z_min and z_max.  To solve for this ratio,
    it is necessary to assume that all antennas see the same opacity.
    The expected change in Tsys between z_min and z_max will then be the
    same for every antenna and polarization.  This range can be selected
    arbitrarily.  This code fits 3rd order polynomials and samples Tsys'
    at z_min = 40 deg and z_max = 62 deg, because these are constrained
    within 5 deg of the tipping scan range (35-67 deg zenith angle).
    (Some things to note:  2nd order polynomials perform poorly for low
    tau0, while higher orders can become biased by noise or spillover
    deviations near the elevation extremes.  Flagging near the elevation
    extremes can bias the polynomial fits.  Fitting an exponential form
    with a multiplicative pre-factor is degenerate.)  For each scan and
    spw, the median delta(Tsys') is taken as the 'true' difference and
    assumed to be correct.  This effectively assumes that the laboratory
    hot/cold load procedures utilized for measuring Tcals yield unbiased
    values that are correct in the median.  Correction factors for the
    Tcals are then obtained from the peculiar ratios relative to the
    median following
    Tcal_true / Tcal_ref = delta(Tsys')_median / delta(Tsys')
    Note that the true Tcals are anticipated to exhibit a few percent
    temperature sensitivity, correlated with Tsurf.
    
    In each case, the code will print to the logger the antenna+electronic
    contributions to Tsys (Tae = Tant+Trx1+Trx2) per scan, antenna, spectral
    window, and polarization.  Summary statistics will also be presented,
    indicating the median, median absolute deviation, min outlier, and max
    outlier over all antennas and polarizations for each scan and spectral
    window.  If you see strange values (e.g. negative, or big difference
    between polarizations) when running with calcTcals=False, or strange
    opacities (e.g. negative), this probably indicates incorrect assumed
    Tcals in the MS.  Try running again with calcTcals=True.  In this case,
    the code will print the new Tcal solutions and their differences against
    the MS Tcals to the logger, as well as associated summary statistics.
    Zenith opacity solutions will be reported to the logger in every case,
    together with summary statistics.  The solutions can be examined using
    plotms.  (WARNING: do not use plotcal because it displays absolute values
    of opacities, and therefore cannot be used to identify negative values.)
    
    Negative Pdif or Psum values will be flagged.  If all data in a given
    scan and polarization for a given antenna and spw are negative, the code
    will report a warning and the relevant opacity will not be calculated.
    Similarly, if there is less than 40 sec of unflagged data for a given
    antenna, spws, scan, and polarization (e.g. following online and manual
    flagging), it will be completely flagged.  You will need to take these
    possibilities into consideration when supplying the resulting zenith
    opacity caltable to applycal.  For example, if you only have one scan
    flagged out of multiple scans, then time interpolation may be suitable
    to avoid unnecessary flagging of correlated data.  However, if you only
    have a single tipping scan, then you will need to consider selecting
    applymode='calflagstrict' to prevent spws from passing through
    uncalibrated and unflagged.  Similarly, this will need to be considered
    following online and manual flagging.
    
    
    Finally, in case you are wondering:  Yes, we can use this approach to
    measure Tcmb.  This is essentially what Penzias and Wilson did.  Cool.
    
    
    
    This code will assume the following:
    * the FEED table specifies dual circularly polarized feeds (R, L)
    for all spectral windows.  This will always be the case for the
    VLA at frequencies where tips are performed.
    * Spectral windows are numbered sequentially from 0 to N
    (though not all spectral windows need to contain tip data)
    * CALDEVICE sub-table NUM_CAL_LOAD=2 (noise tube and solar Tcals,
    where latter will be ignored) for all spws/ants
    * OBSERVATION_ID=0, ARRAY_ID=0, FEED_ID=0, etc (i.e. typical setup)
    
    This task does not support data selection (e.g. spw).  If you care
    about this, select subsets of solutions later in gaincal and applycal.
    
    
    
    Descriptions of keyword arguments are provided at the end of this help file.
    
    
    
    Christopher A. Hales
    Version 1.0 (tested with CASA Version 5.6.0 REL)
    22 October 2019
    
    Pedro P.B. Beaklini
    Version 2.1 (tested with CASA Version 6.4.0.16 REL)
    24 January 2022
    
    Original Code available at: http://github.com/chrishales/tipopac
    tipopac is released under a BSD 3-Clause License; see LICENSE for details.
    
    

    --------- parameter descriptions ---------------------------------------------

    msname    Name of input measurement set
    caltableZ Name of output zenith opacity calibration table
    tauPerAnt Calculate zenith opacity per antenna?
    calcTcals Calculate noise diode temperatures?
    caltableT Name of output Tcal table
    cmdFlag   Apply online flags? (excludes ANTENNA_NOT_ON_SOURCE)
    usrFlag   Apply user-defined flags?
    flagFile  File containing flagging commands (see help for syntax)
    caltable  Create calibration table?
    doPlot    Save plots of the fittings per spw per antenna?
    doModel   Modelling atm to extrapolate tau to all spws?
    [1;42mRETURNS[1;m      void

    --------- examples -----------------------------------------------------------

    
    
    ----- Detailed descriptions of keyword arguments -----
    
    
    Keyword arguments:
    
    
    msname -- Name of input MS or MMS containing switched power data.
    
    
    caltableZ -- Name of output zenith opacity calibration table.
    
    
    tauPerAnt -- If true, zenith opacity will be calculated per antenna.  Otherwise
    a single value will be calculated over the array (per scan and spw).
    
    
    calcTcals     -- If true, tauPerAnt will be set to False to enable calculation of
    noise diode temperatures per polarization, antenna, spw, and scan.
    
    * caltableT -- Name of output Tcal table.  This will be a modified stand-alone
    copy of the CALDEVICE subtable in the MS.  Note that the data
    stored in this table are new Tcal solutions, not delta(Tcal).
    
    
    cmdFlag -- If true, the online flags will be applied to the switched power data
    with the exception of reason=ANTENNA_NOT_ON_SOURCE (otherwise all
    tipping data will be flagged).
    
    
    usrFlag      -- If true, apply user-defined flags from flagFile.
    
    * flagFile -- Text file containing manual flags.  Special syntax is required.
    Each line of the file must specify a particular ant/spw/timerange.
    If you specify additional details (e.g. pol), or don't follow the
    rules below, then the hardcoded interpreter will fail.
    ant: specify either a single antenna name (e.g. 'ea05') or use
    '-1' to indicate that all antennas should be flagged
    spw: specify either a single spectral window (e.g. '7') or use
    '-1' to indicate that all spws should be flagged
    timerange: specify a single UTC range including dates
    For example, contents of myflagfile.txt:
    antenna='ea05' spw='-1' timerange='2019/10/01/08:00:00.0~2019/10/01/08:05:00.0'
    antenna='-1' spw='-1' timerange='2019/10/01/08:05:00.0~2019/10/01/08:10:00.0'
    
    caltable      -- If true, caltable will be crated without needed to run gencal.
    calcTcals set to True. and tauPerAnt set to False.
    It is a test version mode, not recommended for science.
    
    doPlot      -- If true, a dirctory will be created where the plots will be saved.
    It will me saved one plot per antenna per spw.
    
    doModel      -- If true, task will model atmosphere using first K-band opacity followed by
    all tipping scan in the ms file. If true, task will provide an opacity for
    each spw by extrapolation.
    
    
    
    


    """

    _info_group_ = """calibration"""
    _info_desc_ = """Derive zenith opacity and Tcals from JVLA tip data."""

    __schema = {'msname': {'type': 'cReqPath', 'coerce': _coerce.expand_path}, 'caltableZ': {'type': 'cStr', 'coerce': _coerce.to_str}, 'tauPerAnt': {'type': 'cBool'}, 'calcTcals': {'type': 'cBool'}, 'caltableT': {'type': 'cStr', 'coerce': _coerce.to_str}, 'cmdFlag': {'type': 'cBool'}, 'usrFlag': {'type': 'cBool'}, 'flagFile': {'type': 'cStr', 'coerce': _coerce.to_str}, 'caltable': {'type': 'cBool'}, 'doPlot': {'type': 'cBool'}, 'doModel': {'type': 'cBool'}}

    def __init__(self):
        self.__stdout = None
        self.__stderr = None
        self.__root_frame_ = None

    def __globals_(self):
        if self.__root_frame_ is None:
            self.__root_frame_ = _find_frame( )
            assert self.__root_frame_ is not None, "could not find CASAshell global frame"
        return self.__root_frame_

    def __to_string_(self,value):
        if type(value) is str:
            return "'%s'" % value
        else:
            return str(value)

    def __validate_(self,doc,schema):
        return _pc.validate(doc,schema)

    def __do_inp_output(self,param_prefix,description_str,formatting_chars):
        out = self.__stdout or sys.stdout
        description = description_str.split( )
        prefix_width = 23 + 9 + 4
        output = [ ]
        addon = ''
        first_addon = True
        if len(description) == 0:
            out.write(param_prefix + " #\n")
            return
        while len(description) > 0:
            ## starting a new line.....................................................................
            if len(output) == 0:
                ## for first line add parameter information............................................
                if len(param_prefix)-formatting_chars > prefix_width - 1:
                    output.append(param_prefix)
                    continue
                addon = param_prefix + ' #'
                first_addon = True
                addon_formatting = formatting_chars
            else:
                ## for subsequent lines space over prefix width........................................
                addon = (' ' * prefix_width) + '#'
                first_addon = False
                addon_formatting = 0
            ## if first word of description puts us over the screen width, bail........................
            if len(addon + description[0]) - addon_formatting + 1 > self.term_width:
                ## if we're doing the first line make sure it's output.................................
                if first_addon: output.append(addon)
                break
            while len(description) > 0:
                ## if the next description word puts us over break for the next line...................
                if len(addon + description[0]) - addon_formatting + 1 > self.term_width: break
                addon = addon + ' ' + description[0]
                description.pop(0)
            output.append(addon)
        out.write('\n'.join(output) + '\n')

    #--------- return nonsubparam values ----------------------------------------------

    def __doPlot_dflt( self, glb ):
        return False

    def __doPlot( self, glb ):
        if 'doPlot' in glb: return glb['doPlot']
        return False

    def __doModel_dflt( self, glb ):
        return False

    def __doModel( self, glb ):
        if 'doModel' in glb: return glb['doModel']
        return False

    def __usrFlag_dflt( self, glb ):
        return False

    def __usrFlag( self, glb ):
        if 'usrFlag' in glb: return glb['usrFlag']
        return False

    def __caltableT_dflt( self, glb ):
        return ''

    def __caltableT( self, glb ):
        if 'caltableT' in glb: return glb['caltableT']
        return ''

    def __caltable_dflt( self, glb ):
        return False

    def __caltable( self, glb ):
        if 'caltable' in glb: return glb['caltable']
        return False

    def __flagFile_dflt( self, glb ):
        return ''

    def __flagFile( self, glb ):
        if 'flagFile' in glb: return glb['flagFile']
        return ''

    def __tauPerAnt_dflt( self, glb ):
        return False

    def __tauPerAnt( self, glb ):
        if 'tauPerAnt' in glb: return glb['tauPerAnt']
        return False

    def __cmdFlag_dflt( self, glb ):
        return True

    def __cmdFlag( self, glb ):
        if 'cmdFlag' in glb: return glb['cmdFlag']
        return True

    def __msname_dflt( self, glb ):
        return ''

    def __msname( self, glb ):
        if 'msname' in glb: return glb['msname']
        return ''

    def __caltableZ_dflt( self, glb ):
        return ''

    def __caltableZ( self, glb ):
        if 'caltableZ' in glb: return glb['caltableZ']
        return ''

    def __calcTcals_dflt( self, glb ):
        return True

    def __calcTcals( self, glb ):
        if 'calcTcals' in glb: return glb['calcTcals']
        return True



    #--------- return inp/go default --------------------------------------------------


    #--------- return subparam values -------------------------------------------------


    #--------- subparam inp output ----------------------------------------------------
    def __msname_inp(self):
        def xml_default( ):
            ## play the crazy subparameter shell game
            dflt = self.__msname_dflt( self.__globals_( ) )
            if dflt is not None: return dflt
            return ''
        description = ''
        value = self.__msname( self.__globals_( ) )
        (pre,post) = (('','') if value == xml_default( ) else ('\x1B[34m','\x1B[0m')) if self.__validate_({'msname': value},{'msname': self.__schema['msname']}) else ('\x1B[91m','\x1B[0m')
        self.__do_inp_output('%-9.9s = %s%-23s%s' % ('msname',pre,self.__to_string_(value),post),description,0+len(pre)+len(post))
    def __caltableZ_inp(self):
        def xml_default( ):
            ## play the crazy subparameter shell game
            dflt = self.__caltableZ_dflt( self.__globals_( ) )
            if dflt is not None: return dflt
            return ''
        description = ''
        value = self.__caltableZ( self.__globals_( ) )
        (pre,post) = (('','') if value == xml_default( ) else ('\x1B[34m','\x1B[0m')) if self.__validate_({'caltableZ': value},{'caltableZ': self.__schema['caltableZ']}) else ('\x1B[91m','\x1B[0m')
        self.__do_inp_output('%-9.9s = %s%-23s%s' % ('caltableZ',pre,self.__to_string_(value),post),description,0+len(pre)+len(post))
    def __tauPerAnt_inp(self):
        def xml_default( ):
            ## play the crazy subparameter shell game
            dflt = self.__tauPerAnt_dflt( self.__globals_( ) )
            if dflt is not None: return dflt
            return False
        description = ''
        value = self.__tauPerAnt( self.__globals_( ) )
        (pre,post) = (('','') if value == xml_default( ) else ('\x1B[34m','\x1B[0m')) if self.__validate_({'tauPerAnt': value},{'tauPerAnt': self.__schema['tauPerAnt']}) else ('\x1B[91m','\x1B[0m')
        self.__do_inp_output('%-9.9s = %s%-23s%s' % ('tauPerAnt',pre,self.__to_string_(value),post),description,0+len(pre)+len(post))
    def __calcTcals_inp(self):
        def xml_default( ):
            ## play the crazy subparameter shell game
            dflt = self.__calcTcals_dflt( self.__globals_( ) )
            if dflt is not None: return dflt
            return True
        description = ''
        value = self.__calcTcals( self.__globals_( ) )
        (pre,post) = (('','') if value == xml_default( ) else ('\x1B[34m','\x1B[0m')) if self.__validate_({'calcTcals': value},{'calcTcals': self.__schema['calcTcals']}) else ('\x1B[91m','\x1B[0m')
        self.__do_inp_output('%-9.9s = %s%-23s%s' % ('calcTcals',pre,self.__to_string_(value),post),description,0+len(pre)+len(post))
    def __caltableT_inp(self):
        def xml_default( ):
            ## play the crazy subparameter shell game
            dflt = self.__caltableT_dflt( self.__globals_( ) )
            if dflt is not None: return dflt
            return ''
        description = ''
        value = self.__caltableT( self.__globals_( ) )
        (pre,post) = (('','') if value == xml_default( ) else ('\x1B[34m','\x1B[0m')) if self.__validate_({'caltableT': value},{'caltableT': self.__schema['caltableT']}) else ('\x1B[91m','\x1B[0m')
        self.__do_inp_output('%-9.9s = %s%-23s%s' % ('caltableT',pre,self.__to_string_(value),post),description,0+len(pre)+len(post))
    def __cmdFlag_inp(self):
        def xml_default( ):
            ## play the crazy subparameter shell game
            dflt = self.__cmdFlag_dflt( self.__globals_( ) )
            if dflt is not None: return dflt
            return True
        description = ''
        value = self.__cmdFlag( self.__globals_( ) )
        (pre,post) = (('','') if value == xml_default( ) else ('\x1B[34m','\x1B[0m')) if self.__validate_({'cmdFlag': value},{'cmdFlag': self.__schema['cmdFlag']}) else ('\x1B[91m','\x1B[0m')
        self.__do_inp_output('%-9.9s = %s%-23s%s' % ('cmdFlag',pre,self.__to_string_(value),post),description,0+len(pre)+len(post))
    def __usrFlag_inp(self):
        def xml_default( ):
            ## play the crazy subparameter shell game
            dflt = self.__usrFlag_dflt( self.__globals_( ) )
            if dflt is not None: return dflt
            return False
        description = ''
        value = self.__usrFlag( self.__globals_( ) )
        (pre,post) = (('','') if value == xml_default( ) else ('\x1B[34m','\x1B[0m')) if self.__validate_({'usrFlag': value},{'usrFlag': self.__schema['usrFlag']}) else ('\x1B[91m','\x1B[0m')
        self.__do_inp_output('%-9.9s = %s%-23s%s' % ('usrFlag',pre,self.__to_string_(value),post),description,0+len(pre)+len(post))
    def __flagFile_inp(self):
        def xml_default( ):
            ## play the crazy subparameter shell game
            dflt = self.__flagFile_dflt( self.__globals_( ) )
            if dflt is not None: return dflt
            return ''
        description = ''
        value = self.__flagFile( self.__globals_( ) )
        (pre,post) = (('','') if value == xml_default( ) else ('\x1B[34m','\x1B[0m')) if self.__validate_({'flagFile': value},{'flagFile': self.__schema['flagFile']}) else ('\x1B[91m','\x1B[0m')
        self.__do_inp_output('%-9.9s = %s%-23s%s' % ('flagFile',pre,self.__to_string_(value),post),description,0+len(pre)+len(post))
    def __caltable_inp(self):
        def xml_default( ):
            ## play the crazy subparameter shell game
            dflt = self.__caltable_dflt( self.__globals_( ) )
            if dflt is not None: return dflt
            return False
        description = ''
        value = self.__caltable( self.__globals_( ) )
        (pre,post) = (('','') if value == xml_default( ) else ('\x1B[34m','\x1B[0m')) if self.__validate_({'caltable': value},{'caltable': self.__schema['caltable']}) else ('\x1B[91m','\x1B[0m')
        self.__do_inp_output('%-9.9s = %s%-23s%s' % ('caltable',pre,self.__to_string_(value),post),description,0+len(pre)+len(post))
    def __doPlot_inp(self):
        def xml_default( ):
            ## play the crazy subparameter shell game
            dflt = self.__doPlot_dflt( self.__globals_( ) )
            if dflt is not None: return dflt
            return False
        description = ''
        value = self.__doPlot( self.__globals_( ) )
        (pre,post) = (('','') if value == xml_default( ) else ('\x1B[34m','\x1B[0m')) if self.__validate_({'doPlot': value},{'doPlot': self.__schema['doPlot']}) else ('\x1B[91m','\x1B[0m')
        self.__do_inp_output('%-9.9s = %s%-23s%s' % ('doPlot',pre,self.__to_string_(value),post),description,0+len(pre)+len(post))
    def __doModel_inp(self):
        def xml_default( ):
            ## play the crazy subparameter shell game
            dflt = self.__doModel_dflt( self.__globals_( ) )
            if dflt is not None: return dflt
            return False
        description = ''
        value = self.__doModel( self.__globals_( ) )
        (pre,post) = (('','') if value == xml_default( ) else ('\x1B[34m','\x1B[0m')) if self.__validate_({'doModel': value},{'doModel': self.__schema['doModel']}) else ('\x1B[91m','\x1B[0m')
        self.__do_inp_output('%-9.9s = %s%-23s%s' % ('doModel',pre,self.__to_string_(value),post),description,0+len(pre)+len(post))

    #--------- global default implementation-------------------------------------------
    @static_var('state', __sf__('casa_inp_go_state'))
    def set_global_defaults(self):
        self.set_global_defaults.state['last'] = self
        glb = self.__globals_( )
        if 'doPlot' in glb: del glb['doPlot']
        if 'caltableZ' in glb: del glb['caltableZ']
        if 'caltableT' in glb: del glb['caltableT']
        if 'calcTcals' in glb: del glb['calcTcals']
        if 'tauPerAnt' in glb: del glb['tauPerAnt']
        if 'flagFile' in glb: del glb['flagFile']
        if 'doModel' in glb: del glb['doModel']
        if 'usrFlag' in glb: del glb['usrFlag']
        if 'cmdFlag' in glb: del glb['cmdFlag']
        if 'caltable' in glb: del glb['caltable']
        if 'msname' in glb: del glb['msname']


    #--------- inp function -----------------------------------------------------------
    def inp(self):
        print("# tipopac -- %s" % self._info_desc_)
        self.term_width, self.term_height = shutil.get_terminal_size(fallback=(80, 24))
        self.__msname_inp( )
        self.__caltableZ_inp( )
        self.__tauPerAnt_inp( )
        self.__calcTcals_inp( )
        self.__caltableT_inp( )
        self.__cmdFlag_inp( )
        self.__usrFlag_inp( )
        self.__flagFile_inp( )
        self.__caltable_inp( )
        self.__doPlot_inp( )
        self.__doModel_inp( )

    #--------- tget function ----------------------------------------------------------
    @static_var('state', __sf__('casa_inp_go_state'))
    def tget(self,savefile=None):
        from casashell.private.stack_manip import find_frame
        from runpy import run_path
        filename = savefile
        if filename is None:
            filename = "tipopac.last" if os.path.isfile("tipopac.last") else "tipopac.saved"
        if os.path.isfile(filename):
            glob = find_frame( )
            newglob = run_path( filename, init_globals={ } )
            for i in newglob:
                glob[i] = newglob[i]
            self.tget.state['last'] = self
        else:
            print("could not find last file: %s\nsetting defaults instead..." % filename)
            self.set_global_defaults( )

    #--------- tput function ----------------------------------------------------------
    def tput(self,outfile=None):
        def noobj(s):
           if s.startswith('<') and s.endswith('>'):
               return "None"
           else:
               return s

        _postfile = outfile if outfile is not None else os.path.realpath('tipopac.last')

        _invocation_parameters = OrderedDict( )
        _invocation_parameters['msname'] = self.__msname( self.__globals_( ) )
        _invocation_parameters['caltableZ'] = self.__caltableZ( self.__globals_( ) )
        _invocation_parameters['tauPerAnt'] = self.__tauPerAnt( self.__globals_( ) )
        _invocation_parameters['calcTcals'] = self.__calcTcals( self.__globals_( ) )
        _invocation_parameters['caltableT'] = self.__caltableT( self.__globals_( ) )
        _invocation_parameters['cmdFlag'] = self.__cmdFlag( self.__globals_( ) )
        _invocation_parameters['usrFlag'] = self.__usrFlag( self.__globals_( ) )
        _invocation_parameters['flagFile'] = self.__flagFile( self.__globals_( ) )
        _invocation_parameters['caltable'] = self.__caltable( self.__globals_( ) )
        _invocation_parameters['doPlot'] = self.__doPlot( self.__globals_( ) )
        _invocation_parameters['doModel'] = self.__doModel( self.__globals_( ) )

        try:
            with open(_postfile,'w') as _f:
                for _i in _invocation_parameters:
                    _f.write("%-9s = %s\n" % (_i,noobj(repr(_invocation_parameters[_i]))))
                _f.write("#tipopac( ")
                count = 0
                for _i in _invocation_parameters:
                    _f.write("%s=%s" % (_i,noobj(repr(_invocation_parameters[_i]))))
                    count += 1
                    if count < len(_invocation_parameters): _f.write(",")
                _f.write(" )\n")
        except: return False
        return True

    def __call__( self, msname=None, caltableZ=None, tauPerAnt=None, calcTcals=None, caltableT=None, cmdFlag=None, usrFlag=None, flagFile=None, caltable=None, doPlot=None, doModel=None ):
        def noobj(s):
           if s.startswith('<') and s.endswith('>'):
               return "None"
           else:
               return s
        _prefile = os.path.realpath('tipopac.pre')
        _postfile = os.path.realpath('tipopac.last')
        _return_result_ = None
        _arguments = [msname,caltableZ,tauPerAnt,calcTcals,caltableT,cmdFlag,usrFlag,flagFile,caltable,doPlot,doModel]
        _invocation_parameters = OrderedDict( )
        if any(map(lambda x: x is not None,_arguments)):
            # invoke python style
            # set the non sub-parameters that are not None
            local_global = { }
            if msname is not None: local_global['msname'] = msname
            if caltableZ is not None: local_global['caltableZ'] = caltableZ
            if tauPerAnt is not None: local_global['tauPerAnt'] = tauPerAnt
            if calcTcals is not None: local_global['calcTcals'] = calcTcals
            if caltableT is not None: local_global['caltableT'] = caltableT
            if cmdFlag is not None: local_global['cmdFlag'] = cmdFlag
            if usrFlag is not None: local_global['usrFlag'] = usrFlag
            if flagFile is not None: local_global['flagFile'] = flagFile
            if caltable is not None: local_global['caltable'] = caltable
            if doPlot is not None: local_global['doPlot'] = doPlot
            if doModel is not None: local_global['doModel'] = doModel

            # the invocation parameters for the non-subparameters can now be set - this picks up those defaults
            _invocation_parameters['msname'] = self.__msname( local_global )
            _invocation_parameters['caltableZ'] = self.__caltableZ( local_global )
            _invocation_parameters['tauPerAnt'] = self.__tauPerAnt( local_global )
            _invocation_parameters['calcTcals'] = self.__calcTcals( local_global )
            _invocation_parameters['caltableT'] = self.__caltableT( local_global )
            _invocation_parameters['cmdFlag'] = self.__cmdFlag( local_global )
            _invocation_parameters['usrFlag'] = self.__usrFlag( local_global )
            _invocation_parameters['flagFile'] = self.__flagFile( local_global )
            _invocation_parameters['caltable'] = self.__caltable( local_global )
            _invocation_parameters['doPlot'] = self.__doPlot( local_global )
            _invocation_parameters['doModel'] = self.__doModel( local_global )

            # the sub-parameters can then be set. Use the supplied value if not None, else the function, which gets the appropriate default
            

        else:
            # invoke with inp/go semantics
            _invocation_parameters['msname'] = self.__msname( self.__globals_( ) )
            _invocation_parameters['caltableZ'] = self.__caltableZ( self.__globals_( ) )
            _invocation_parameters['tauPerAnt'] = self.__tauPerAnt( self.__globals_( ) )
            _invocation_parameters['calcTcals'] = self.__calcTcals( self.__globals_( ) )
            _invocation_parameters['caltableT'] = self.__caltableT( self.__globals_( ) )
            _invocation_parameters['cmdFlag'] = self.__cmdFlag( self.__globals_( ) )
            _invocation_parameters['usrFlag'] = self.__usrFlag( self.__globals_( ) )
            _invocation_parameters['flagFile'] = self.__flagFile( self.__globals_( ) )
            _invocation_parameters['caltable'] = self.__caltable( self.__globals_( ) )
            _invocation_parameters['doPlot'] = self.__doPlot( self.__globals_( ) )
            _invocation_parameters['doModel'] = self.__doModel( self.__globals_( ) )
        try:
            with open(_prefile,'w') as _f:
                for _i in _invocation_parameters:
                    _f.write("%-9s = %s\n" % (_i,noobj(repr(_invocation_parameters[_i]))))
                _f.write("#tipopac( ")
                count = 0
                for _i in _invocation_parameters:
                    _f.write("%s=%s" % (_i,noobj(repr(_invocation_parameters[_i]))))
                    count += 1
                    if count < len(_invocation_parameters): _f.write(",")
                _f.write(" )\n")
        except: pass
        try:
            _return_result_ = _tipopac_t( _invocation_parameters['msname'],_invocation_parameters['caltableZ'],_invocation_parameters['tauPerAnt'],_invocation_parameters['calcTcals'],_invocation_parameters['caltableT'],_invocation_parameters['cmdFlag'],_invocation_parameters['usrFlag'],_invocation_parameters['flagFile'],_invocation_parameters['caltable'],_invocation_parameters['doPlot'],_invocation_parameters['doModel'] )
        except Exception as e:
            from traceback import format_exc
            from casatasks import casalog
            casalog.origin('tipopac')
            casalog.post("Exception Reported: Error in tipopac: %s" % str(e),'SEVERE')
            casalog.post(format_exc( ))
            _return_result_ = False
        try:
            os.rename(_prefile,_postfile)
        except: pass
        return _return_result_

tipopac = _tipopac( )

